//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.CannedResponses {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.CannedResponses.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しく追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddNewButtonText {
            get {
                return ResourceManager.GetString("AddNewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題が発生しました。もう一度提案してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddNewSuggestionFailedMessage {
            get {
                return ResourceManager.GetString("AddNewSuggestionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   提案が追加されました！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddNewSuggestionSuccessMessage {
            get {
                return ResourceManager.GetString("AddNewSuggestionSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題が発生しました。もう一度回答を追加してみてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddUserResponseFailedMessage {
            get {
                return ResourceManager.GetString("AddUserResponseFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に追加されました！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddUserResponseSuccessMessage {
            get {
                return ResourceManager.GetString("AddUserResponseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   承認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApproveButtonTitle {
            get {
                return ResourceManager.GetString("ApproveButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   承認済み: {0} by {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApprovedAdminCardLabelText {
            get {
                return ResourceManager.GetString("ApprovedAdminCardLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   承認済み: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApprovedCardLabelText {
            get {
                return ResourceManager.GetString("ApprovedCardLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **リクエストを承認** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApprovedRequestRefreshCardTitle {
            get {
                return ResourceManager.GetString("ApprovedRequestRefreshCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   承認済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApprovedRequestStatusText {
            get {
                return ResourceManager.GetString("ApprovedRequestStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApproveToggleCardCategoryTitle {
            get {
                return ResourceManager.GetString("ApproveToggleCardCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリーを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApproveToggleCardLabelPlaceholder {
            get {
                return ResourceManager.GetString("ApproveToggleCardLabelPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   質問をセミコロン（;）で区切って入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApproveToggleCardQuestionsPlaceholder {
            get {
                return ResourceManager.GetString("ApproveToggleCardQuestionsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   質問 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApproveToggleCardQuestionsTitle {
            get {
                return ResourceManager.GetString("ApproveToggleCardQuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答を入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApproveToggleCardResponsePlaceholder {
            get {
                return ResourceManager.GetString("ApproveToggleCardResponsePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApproveToggleCardResponseTitle {
            get {
                return ResourceManager.GetString("ApproveToggleCardResponseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApproveToggleCardSubmitButtonTitle {
            get {
                return ResourceManager.GetString("ApproveToggleCardSubmitButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}とチャット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChatTextButton {
            get {
                return ResourceManager.GetString("ChatTextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社の回答 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyResponsesMenuText {
            get {
                return ResourceManager.GetString("CompanyResponsesMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmButtonText {
            get {
                return ResourceManager.GetString("ConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクション確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogConfirmHeader {
            get {
                return ResourceManager.GetString("DialogConfirmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアクションを確認してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogConfirmText {
            get {
                return ResourceManager.GetString("DialogConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題が発生しました。もう一度更新してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditUserResponseFailedMessage {
            get {
                return ResourceManager.GetString("EditUserResponseFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新を保存しました！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditUserResponseSuccessMessage {
            get {
                return ResourceManager.GetString("EditUserResponseSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題が発生しました。数分後にもう一度お試しください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答を承認するには、カテゴリー、質問、回答のフィールドが必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessageOnApprove {
            get {
                return ResourceManager.GetString("ErrorMessageOnApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリはボットコマンドをサポートしていません。より良い結果を得るには、メッセージング拡張機能を使用してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorWhenMessageInChannel {
            get {
                return ResourceManager.GetString("ErrorWhenMessageInChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この項目は必須です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FieldRequiredMessage {
            get {
                return ResourceManager.GetString("FieldRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このページにはアクセスできません。許可については、IT管理者にお問い合わせください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ForbiddenErrorMessage {
            get {
                return ResourceManager.GetString("ForbiddenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題が発生しています。数分後にもう一度お試しください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答を管理する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManageYourResponsesTitleText {
            get {
                return ResourceManager.GetString("ManageYourResponsesTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   承認された会社の回答が上限に達しました。詳細については、管理者にお問い合わせください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaxCompanyResponseMessage {
            get {
                return ResourceManager.GetString("MaxCompanyResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大200のユーザー回答を作成できます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaxResponsesMessage {
            get {
                return ResourceManager.GetString("MaxResponsesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたの回答 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MyResponsesText {
            get {
                return ResourceManager.GetString("MyResponsesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **企業の回答を提案していただきありがとうございます。** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationCardApprovedOrRejectedTitle {
            get {
                return ResourceManager.GetString("NotificationCardApprovedOrRejectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **カテゴリー:** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationCardLabelText {
            get {
                return ResourceManager.GetString("NotificationCardLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **質問:** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationCardQuestion {
            get {
                return ResourceManager.GetString("NotificationCardQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **コメント** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationCardRemark {
            get {
                return ResourceManager.GetString("NotificationCardRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **リクエストは却下されました** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationCardRequestReject {
            get {
                return ResourceManager.GetString("NotificationCardRequestReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   提案 by {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationCardRequestText {
            get {
                return ResourceManager.GetString("NotificationCardRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **回答:** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationCardResponse {
            get {
                return ResourceManager.GetString("NotificationCardResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータス: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationCardStatusText {
            get {
                return ResourceManager.GetString("NotificationCardStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **新着！会社の回答の承認依頼** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationRequestCardContentText {
            get {
                return ResourceManager.GetString("NotificationRequestCardContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   質問 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   質問 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   提案 by {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshedNotificationCardRequestText {
            get {
                return ResourceManager.GetString("RefreshedNotificationCardRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リフレッシュ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshLinkText {
            get {
                return ResourceManager.GetString("RefreshLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   却下 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RejectButtonTitle {
            get {
                return ResourceManager.GetString("RejectButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   却下: {0} by {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RejectedAdminCardLabelText {
            get {
                return ResourceManager.GetString("RejectedAdminCardLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   却下されました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RejectedCardLabelText {
            get {
                return ResourceManager.GetString("RejectedCardLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   却下されました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RejectedRequestStatusText {
            get {
                return ResourceManager.GetString("RejectedRequestStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   これが却下された理由を説明してください（オプション） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RejectToggleCardRemarkPlaceholder {
            get {
                return ResourceManager.GetString("RejectToggleCardRemarkPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RejectToggleCardRemarkTitle {
            get {
                return ResourceManager.GetString("RejectToggleCardRemarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RejectToggleCardSubmitButtonTitle {
            get {
                return ResourceManager.GetString("RejectToggleCardSubmitButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要求日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestedOnText {
            get {
                return ResourceManager.GetString("RequestedOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestsMenuText {
            get {
                return ResourceManager.GetString("RequestsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   提案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SuggestButtonText {
            get {
                return ResourceManager.GetString("SuggestButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しい提案 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SuggestNewButtonText {
            get {
                return ResourceManager.GetString("SuggestNewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリーを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TypeCategoryPlaceholder {
            get {
                return ResourceManager.GetString("TypeCategoryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   質問をセミコロン（;）で区切って入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TypeQuestionPlaceholder {
            get {
                return ResourceManager.GetString("TypeQuestionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答を入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TypeResponsePlaceholder {
            get {
                return ResourceManager.GetString("TypeResponsePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題が発生しています。数分後にもう一度お試しください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnauthorizedErrorMessage {
            get {
                return ResourceManager.GetString("UnauthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新を送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateAndShareButtonText {
            get {
                return ResourceManager.GetString("UpdateAndShareButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateButtonText {
            get {
                return ResourceManager.GetString("UpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   こんにちは、ボットコマンドはサポートしていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserCustomMessage {
            get {
                return ResourceManager.GetString("UserCustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -依頼者とチャットします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardChatRequestorContentText {
            get {
                return ResourceManager.GetString("WelcomeCardChatRequestorContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始するには、チャットメッセージ入力欄の下にあるアイコン一覧より本アプリのアイコンをクリックしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardContent {
            get {
                return ResourceManager.GetString("WelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   こんにちは、ユーザーが送信した回答の管理をお手伝いします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardContentForAdmin {
            get {
                return ResourceManager.GetString("WelcomeCardContentForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - 最終的な送信の前に回答を編集します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardLabelContentText {
            get {
                return ResourceManager.GetString("WelcomeCardLabelContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - 個人的な回答を管理します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardResponseListContentText {
            get {
                return ResourceManager.GetString("WelcomeCardResponseListContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - 会社全体で使用する新しい回答を提案し、リクエストのステータスを確認します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardSuggestedContentText {
            get {
                return ResourceManager.GetString("WelcomeCardSuggestedContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - 会社の回答に新しい回答を提案します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardSuggestResponseContentText {
            get {
                return ResourceManager.GetString("WelcomeCardSuggestResponseContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本アプリでは以下のことが可能です: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardThingsContentText {
            get {
                return ResourceManager.GetString("WelcomeCardThingsContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ようこそ！チャットメッセージでの共有に対する検索と迅速な回答を管理するお手伝いをします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
    }
}
